### ISSUE TITLE
Decide on CSS parser for CSS processing rules.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#10]
Let's investigate what's state of the art in CSS parsing for Node. Then the next step will be to prototype out something simple and double check the chosen solutions looks fit for purpose.

**Comment by muffinresearch** [comment]
This looks worth a closer look:

* https://github.com/reworkcss/css

**Comment by tofumatt** [comment]
This was the one I found when looking too, I _think_ it should do the trick.

**Comment by muffinresearch** [comment]
I'll file a new bug for trying it out - otherwise this is good.
