### ISSUE TITLE
Plan architecture for processing files.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#11]
Starting with the xpi:

* How with the various parsers and processors be glued together. 
* We should look to ensure the integrity of the scans (making sure all files are processed).

**Comment by muffinresearch** [comment]
I'm thinking making use of Promises throughout will make sense.

**Comment by tofumatt** [comment]
+1 I love the promises API and it will make sense when we have objects we want to pass throw a series of discrete tests/rules.



- tofumatt

**Comment by muffinresearch** [comment]
So far we have:

* Use promises for Async
* Use streams wherever possible.

Any other considerations?

**Comment by tofumatt** [comment]
We said on vidyo we want to keep from having file handlers open and that we would open/close files in the background, we could add that in here as a point.

Otherwise it’s complete.

**Comment by muffinresearch** [comment]
Ok, I'll move this to the wiki and then we can call this done.

**Comment by tofumatt** [comment]
👍

- tofumatt

On 28 September 2015 at 15:19:12, Stuart Colville (notifications@github.com) wrote:

Ok, I'll move this to the wiki and then we can call this done.

**Comment by muffinresearch** [comment]
Documented here: https://github.com/mozilla/addons-validator/wiki/File-processing-considerations
