### ISSUE TITLE
Exclude rule functions that start with '_' from being run.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#128]
The rdf scanner has this feature it would be nice to make that common across the board.

https://github.com/mozilla/addons-validator/blob/master/src/validators/rdf.js#L31

**Comment by tofumatt** [comment]
This partially relates to #83; in reality we should have all classes doing this, probably with some kind of `utils` function shared amongst all classes.

**Comment by muffinresearch** [comment]
Yep, :+1:  to it being shared code.
