### ISSUE TITLE
Tests should fail without 100% test coverage

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#135]
It would be nice if tests coverage could return an error if not at 100%; it'd be an easy way to test in a PR if the code quality is up to our current 100% coverage standards.

**Comment by muffinresearch** [comment]
This should do that I think (I've just changed the settings):

<img width="174" alt="mozilla_addons-validator___coveralls_-_test_coverage_history___statistics" src="https://cloud.githubusercontent.com/assets/1514/10660217/41a24368-789d-11e5-96c8-72113d5544fb.png">

**Comment by muffinresearch** [comment]
I'll try submitting a branch with bad coverage and see...

**Comment by muffinresearch** [comment]
Yep - coveralls caught it.

<img alt="test_missing_coverage_by_muffinresearch_ _pull_request__137_ _mozilla_addons-validator" src="https://cloud.githubusercontent.com/assets/1514/10660881/2e977252-78a2-11e5-9fab-3e4731de50f4.png">

**Comment by tofumatt** [comment]
Awesome, thanks :smile:
