### ISSUE TITLE
Consider the use-case for notices

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#155]
Eslint only supports warning and errors so our JS rules are going to need to follow that or we're going to need to work around it. 

It makes me thing do we have a solid use-case for notices in the new validator. What's the actual difference between a notice and a warning for the purposes of validation?

**Comment by tofumatt** [comment]
For what it's worth, I don't see a use-case for them. An error means it's _no bueno_, and a warning means it's something that would pass validation _maybe_ but certainly worth a look. Notices in the old validator are potential security issues that'd I'd certainly call a "warning" and not a "notice".

A notice feels like a polite warning in this set of messages; not really needed :wink:

**Comment by tofumatt** [comment]
Looks like we are going to use notices, so I think we can close this.

**Comment by muffinresearch** [comment]
yep
