### ISSUE TITLE
Enable es6 in checking

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-validator#181]
Both of my add-ons use ES6, so that currently means the validator throws errors on every JS file. Would it be possible to cope with ES6?

**Comment by tofumatt** [comment]
The plan is to allow them, we just have to enable it. I believe a PR from nolski actually enables it, just not in master yet.

- tofumatt (Sent from mobile)

**Comment by muffinresearch** [comment]
Nolski's patch is pretty much ready to land, so I'd expect that to be fixed today.
