### ISSUE TITLE
unexpectedSuccess should be imported from tests/helpers not src/utils

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#187]
~~The `unexpectedSuccess` helper is only used in tests but is located in `src/utils.js`.~~

~~It should be moved to `tests/helpers.js` to keep things consistent/organised.~~

Some imports for `unexpectedSuccess` are using it from `utils` not `tests/helpers`. As this isn't ever called it went unnoticed that the import will be undefined.

**Comment by muffinresearch** [comment]
Is it? It's here: https://github.com/mozilla/addons-validator/blob/master/tests/helpers.js#L62

**Comment by tofumatt** [comment]
I didn’t get an error when I imported it from utils! I am surprised!

**Comment by muffinresearch** [comment]
Yeah, presumably it's just undefined. You'd only get an error when you use it.

**Comment by tofumatt** [comment]
Which _should_ never happen. Interesting! :-)

**Comment by tofumatt** [comment]
Rather, it should be *imported* from `tests/helper.js`. It's not in README, at least. I'm reopening and I'll fix it to close this issue.

**Comment by muffinresearch** [comment]
Oops - yeah must have missed that it crept in here https://github.com/mozilla/addons-validator/commit/c042f075fdf0f85bb5f66b61f7ac3bcf1b1ca29d

Also the readme is wrong.

**Comment by muffinresearch** [comment]
> Rather, it should be imported from tests/helper.js. It's not in README, at least. I'm reopening and I'll fix it to close this issue.

Cool - I've renamed this appropriately.
