### ISSUE TITLE
Pass metadata to rule functions

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#190]
When #152 lands let's work out how to pass the metadata like add-on type. I think there's going to be quite a lot of it so maybe passing the validation instance might start to make more sense.

**Comment by tofumatt** [comment]
My simple solution was to attach it to the XPI in https://github.com/mozilla/addons-validator/pull/230; I think of the XPI object as the "add-on", but maybe that's a bit off.

The XPI already has a `metadata` properly so I put it in there. Determining the add-on type and metadata requires scanners and other things too, but putting that info in the XPI makes sense to me. It seems the simplest solution so I gravitated toward it, but I haven't actually had to use the data yet, so maybe there are obvious pitfalls I don't see.

**Comment by tofumatt** [comment]
Right now we're assigning all the metadata to an object at `validatorInstance.metadata`, which I think makes sense. Passing in just that object, rather than the whole `validatorInstance` helps us pass around too much global scope which I think is good.

**Comment by muffinresearch** [comment]
It's `Validator.addonMetaData` https://github.com/mozilla/addons-validator/blob/master/src/validator.js#L356 - we're taking about addon metadata as opposed to files here.

**Comment by tofumatt** [comment]
Yup, that’s what I’m thinking :-)
