### ISSUE TITLE
Detect JPM addons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#192]
Needed to provide more metadata.

**Comment by tofumatt** [comment]
I just created an add-on using `jpm init` and it seems to be a Jetpack add-on with no special signifiers that it was made with JPM. What's the use-case for knowing something was made with JPM?

We could get `jpm xpi` to add a property in the `install.rdf` that allowed us to mark something as a JPM add-on. Right now the only thing that we could check is the `bootstrap.js` file jpm seems to add.

**Comment by muffinresearch** [comment]
There's code in the old validator - we could look at that and see how that works. 

This was the code - https://github.com/mozilla/amo-validator/blob/c239e55352f55a69bfd085e7f0e9279b40ced673/validator/testcases/javascript/actions.py#L526

**Comment by tofumatt** [comment]
Ah, cool. I'll have a look when I'm back from the gym in an hour or so. 

- tofumatt (Sent from mobile)

**Comment by tofumatt** [comment]
Ah okay, I found it. Seems anything with a `bootstrap.js` and a `package.json` is considered a Jetpack add-on... so this is a JPM add-on then?

(Is JPM a synonym for Jetpack in this issue?)

**Comment by muffinresearch** [comment]
> (Is JPM a synonym for Jetpack in this issue?)

Yep, because jpm is this module https://www.npmjs.com/package/jpm

**Comment by tofumatt** [comment]
Cool, sorry for being daft. I was just not quite following.

**Comment by muffinresearch** [comment]
> Cool, sorry for being daft. I was just not quite following.

No, it's fine - I should put more detail in the issues!

Would the lib detection stuff help make this more robust? I think the old code looks at hashes of SDK lib versions as well as other things.

**Comment by tofumatt** [comment]
That’d be cool, but possibly a follow-up issue. Feature-parity is easier.

After doing some digging the tests seem to test only for the existence of bootstrap.js: https://github.com/mozilla/amo-validator/blob/7a8011aba8bf8c665aef2b51eb26d0697b3e19c3/tests/test_jetpack.py#L49

**Comment by muffinresearch** [comment]
Yeah I know what you mean. Parity is one thing but I do think if something feels obviously brittle we can look at better ways to do things.

**Comment by tofumatt** [comment]
I agree actually. I thought “surely this can’t be all it takes to be considered a Jetpack add-on” when I saw the test.

I’ll at least implement it the old way to start, then I’ll look at the hash of libs maybe and use that prior art for getting hashes of bootstrap too.
