### ISSUE TITLE
Setup eslint settings

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#2]

**Comment by mozfreddyb** [comment]
Hey Stuart!
I've been working on setting up eslint for our gaia build process ([bug 1159667](https://bugzilla.mozilla.org/show_bug.cgi?id=1159667)).
I'd be happy to help here, if I can.

We (the FxOS security team) may want to squeeze in some security checks in the future, by adding eslint-plugins to your eslintrc, if that's alright ;)

**Comment by mozfreddyb** [comment]
Oops. I am assuming that you use eslint to do the addons validation, not just about setting up eslint to check the source of the addons-validator ;-)

**Comment by muffinresearch** [comment]
This is just about eslint for our code. But yeah I like sound of using eslint for the js validation bits.
