### ISSUE TITLE
Fix up the npm package

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#201]
Currently working through the issues on the npm package

* [x] Fix the dist/addons-validator.js being present
* [x] Ignore more things
* [x] Add a bin entry
* [x] Fix support for missing source-map-support dep (it was in devDeps not deps).
* [x] Fix path to rules for running as binary + tests

**Comment by muffinresearch** [comment]
Confirmed having installed 0.0.5 it works from `node_modules/.bin/addons-validator` or `node_modules/addons-validator/bin/addons-validator`.

**Comment by tofumatt** [comment]
Yay for iteration! 👍
