### ISSUE TITLE
Add JSCS to tests

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#21]
I've already made a few silly style nitpicks/raised some style questions in #20.

Shall we add some [JS Style checks](https://github.com/jscs-dev/node-jscs) to the tests so we don't quibble over how we do long strings, line lengths, etc.?

It's worked well for localForage. Keeps styles in-line on the more fluid things eslint won't check.

**Comment by muffinresearch** [comment]
Yeah sound good - especially if helps with code-review.
