### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined when validating bootstrap.js add-on

### ISSUE THREAD

**Issue by leibovic** [mozilla/addons-validator#217]
I see this error when running the validator against this XPI:
http://people.mozilla.org/~mleibovic/test/coach.xpi

I'm running v0.0.5, installed via npm.

**Comment by muffinresearch** [comment]
Ok - I've found the cause. We're not currently handling media rules.

**Comment by muffinresearch** [comment]
@leibovic Tagged version 0.0.6 should be up on npm shortly with the fix for this issue. Thanks for the report.

**Comment by leibovic** [comment]
Thanks! This works for me now.

**Comment by minj** [comment]
Got the same error here.

Installed with npm -g

Add-ons Validator (JS Edition) v0.0.7
npm v3.4.0

**Comment by muffinresearch** [comment]
@minj hi - please can you open a new bug with full STR and an a link  to addon code that produces that error?

**Comment by minj** [comment]
@muffinresearch done
