### ISSUE TITLE
Use print() inside extractMetaData

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#254]
We're using `console.log` in https://github.com/mozilla/addons-validator/blob/master/src/validator.js#L347, meaning the test output includes a stray "undefined", which I thought was my fault from testing in a PR :wink: 

We should make this use the Validator's `print` method so we can easily silence it in tests.

<img width="281" alt="screenshot 2015-11-13 18 32 51" src="https://cloud.githubusercontent.com/assets/90871/11152812/02240a2e-8a35-11e5-8592-e74315231191.png">

**Comment by muffinresearch** [comment]
Ok - cool I'll take a look at fixing this, since I introduced it.
