### ISSUE TITLE
Settle on metadata or metaData

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#261]
Re: camelCase or not of the word metadata.

I prefer the first (it's one word), but we should just be consistent in the code, which we aren't right now.

**Comment by muffinresearch** [comment]
Good catch. It should be 'metadata' as you say it *is* one word. 

So to fix this we should wait for the couple of metadata related patches to land and then do `s/MetaData/Metadata/` and `s/metaData/metadata/`
