### ISSUE TITLE
Mark empty files so olympia source viewer can ignore them

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-validator#334]
The old amo-validator ignores files that are on our checksum list. They get greyed out in the olympia source viewer and a note about the recognized library shows in the validation report.

For empty files, we also want the addons-validator to recognize such files so the source viewer can grey them as well, but the HTML validation report on olympia should *not* list the empty file, because that's irrelevant.

**Comment by muffinresearch** [comment]
It's not clear to me what needs to happen here. What do you mean by mark empty files?

**Comment by wagnerand** [comment]
Using screenshots here as access to reproduce on prod might be limited:

The following is a screenshot of the source viewer tool on AMO (e.g https://addons.mozilla.org/en-US/firefox/files/browse/370800/):
<img width="271" alt="lib" src="https://cloud.githubusercontent.com/assets/873258/11408717/42fd8e00-93bb-11e5-9bac-a31cf78dc0c2.png">
As you can see, the file `bootstrap.js` is greyed out because the validator has recognized it as a "known library", in this case from `Jetpack` (see tooltip), based on our whitelists.

For each of such known libraries, the validation report contains one entry:
<img width="964" alt="report" src="https://cloud.githubusercontent.com/assets/873258/11408819/e1c767cc-93bb-11e5-9a74-06309cc609d9.png">

So, what we want for empty files is to have the former (being greyed out), but not the latter (validation report entry).

**Comment by muffinresearch** [comment]
Ok so the validator side of this should just be to determine zero byte files and flag them somehow.

**Comment by wagnerand** [comment]
Yes.
