### ISSUE TITLE
Does the validator need to be localized?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#40]
I see the current validator isn't - but I wondered if that might make sense.

**Comment by tofumatt** [comment]
Need is probably a strong word, but no reason not to build it with that it mind. I don't mind going through all the strings and wrapping them in gettext or whatnot.

- tofumatt (Sent from mobile)

**Comment by muffinresearch** [comment]
I've not seen / heard a requirement  for this but in terms of improving the add-on ecosystem it seems like it would be nice if the tool was localized both when used from the web and as a cli tool.

**Comment by tofumatt** [comment]
It should be minimal effort to do, so let's add it to the next sprint. I'll take it on then.

**Comment by tofumatt** [comment]
NOTE: Explore es6 gettext/translating template string.

**Comment by muffinresearch** [comment]
Going to raise a new issue for the last point re: tags and templating for l10n in es6. Otherwise we have consensus that we'll at a minimum wrap strings in gettext as we go.
