### ISSUE TITLE
Connect up express so we start building out an API.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-validator#49]
Add express into the mix so we're starting to look at non-CLI based consumption of our code.

Initial steps are going to be to handle an incoming package and hand that off to the Validator.

**Comment by muffinresearch** [comment]
Thinking more about this - I'm not convinced this would be the right approach. Do we really want something that does validation in a request? 

I don't know how the current setup works precisely but shouldn't validation be queued and dealt with by validation workers? If so we probably don't need an API unless the queue and workers need to be dealt with outside of AMO in which case this is a much bigger bug.

**Comment by tofumatt** [comment]
Yeah, this makes sense. I think the website might be a cool demo, but an HTTP API for validation wouldn't be world-facing.

This then becomes a bit of an add-ons rewrite question. If we want to do a bunch of micro-services that all talk HTTP to one another, writing a request-based API could be a thing, but even then the worker idea seems saner.

I could imagine an API that accepts a file and gives back a "validation request ID" one could poll for results with. But not a validation tied to the request/response cycle. Seems like an invitation for a timeout error if nothing else.

**Comment by tofumatt** [comment]
An aside re: "making sure we aren't too CLI":

Part of the intent to this bug was making sure we weren't too CLI-focused. But we started by outputting JSON before we even had pretty CLI output, so we are at least able to send our validation results off to places as-is.

**Comment by tofumatt** [comment]
We don't want to build an Express API after all; what we really want is the ability to interact with Celery and run this in a queue from Olympia.

I'll close this as I don't think it's actually needed anymore; we don't need a **direct** web interface to the validator.
