### ISSUE TITLE
Put scanners/validators in their own directory

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#59]
Just a minor thought, but as we add separate scanners (CSS, JS, RDF), the root of `src/` is getting crowded. It would be easier to see what files did what if they were grouped (ie put all scanners in a `scanners/` folder.

So instead of:

```
- src/
  - messages/
  - rules/
  - cli.js
  - css.js
  - javascript.js
  - rdf.js
  [etc.]
```
we can do:
```
- src/
  - messages/
  - scanners/
    - css.js
    - javascript.js
    - rdf.js
  - rules/
  - cli.js
  [etc.]
```

**Comment by muffinresearch** [comment]
:+1:  sounds like a plan.
