### ISSUE TITLE
Make tests less noisy

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#69]
Output from the tests is a bit noisy because we have `console.log` calls inside the code path that aren't silenced for tests.

<img width="572" alt="screenshot 2015-10-09 21 00 55" src="https://cloud.githubusercontent.com/assets/90871/10404188/ddac89d2-6ec8-11e5-87fe-2aaffef3813e.png">

Realistically, we probably want an `validator.config.output` option that is `nothing` or `null`.

Not sure when the CLI would ever want it, but it's what we want for the tests and we should already have the infra for it via that `config.output` option.

Other `console.log` should be silenced by this option. We probably just want to use our own `log` method everywhere.

**Comment by muffinresearch** [comment]
Yeah - good call on raising this bug - I was thinking the same thing about looking to remove the clutter from tests.
