### ISSUE TITLE
Test to make sure number of rules match rules that are run in scan()

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-validator#85]
Write a test that checks the number of rule files in `rules/$VALIDATOR_TYPE` (eg: all files sans `index.js`) and checks how many rules are run in `$VALIDATOR_TYPE.scan()`. We can test this for at least the HTML and RDF checkers now, and could check the length of the ESLint rule list as well.

This makes sure of two things:

1. All rule files contain _exactly_ one rule.
2. All rules are being exported/imported and run properly.

**Comment by muffinresearch** [comment]
This is a really good idea.
